services:
  - type: web
    name: minecraft-manager
    env: docker
    dockerfilePath: docker/controller.Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JAVA_MIN_MEMORY
        value: 512M
      - key: JAVA_MAX_MEMORY
        value: 1G
      - key: DATABASE_URL
        value: # URL DE TU BASE DE DATOS MYSQL (Ej: mysql://user:pass@host:3306/db)
